In [2]:
import pandas as pd
import sys
sys.path.insert(0,'../statistics_helper/')
from stats_helper import *
from CI_helper import *

In [1]:
raw_data = pd.read_excel('../results/results.xlsx','Data')

In [3]:
raw_data

,Taxon,Kingdom,Group,Cellularity,Location,Trophic mode,Biomass,Uncertainty,Reference
0,Seagrass,plants,NaN,Multi,Benthic,Auto,0.189737,3.892861,This study
1,Plant macroalgae,plants,NaN,Multi,Benthic,Auto,0.208989,4.657959,This study
2,Bacterial phytoplankton,bacteria,NaN,Uni,Plankton,Auto,0.194478,NaN,This study
3,Green algae phytoplankton,plants,NaN,Uni,Plankton,Auto,0.103381,3.622760,This study
4,Protist phytoplankton,protists,NaN,Uni,Plankton,Auto,0.307346,9.254570,This study
5,Marine bacteria,bacteria,NaN,Uni,Plankton,Hetero,1.132457,1.811229,Bar-On et al.
6,Marine archaea,archaea,NaN,Uni,Plankton,Hetero,0.331734,2.688034,Bar-On et al.
7,Mesozooplankton,animals,Copepods,Multi,Plankton,Hetero,0.564510,10.000000,Bar-On et al.
8,Macrozooplankton (only crustaceans),animals,NaN,Multi,Plankton,Hetero,0.375738,10.000000,Bar-On et al.
9,Pteropods,animals,NaN,Multi,Plankton,Hetero,0.131985,10.000000,Bar-On et al.
10,Cnidaria (jellyfish),animals,NaN,Multi,Plankton,Hetero,0.039997,10.000000,Bar-On et al.
11,Cnidaria (corals),animals,NaN,Multi,Benthic,Hetero,0.049620,10.000000,Bar-On et al.
12,Molluscs (squid),animals,NaN,Multi,Nekton,Hetero,0.050000,10.000000,Bar-On et al.
13,Wild marine mammals,animals,NaN,Multi,Nekton,Hetero,0.004454,NaN,Bar-On et al.
14,Nematodes,animals,NaN,Multi,Benthic,Hetero,0.014000,10.000000,Bar-On et al.
15,Fish,animals,Fish,Multi,Nekton,Hetero,0.557122,6.956249,This study
16,Microzooplankton,protists,NaN,Uni,Plankton,Hetero,0.592000,10.000000,Bar-On et al.
17,Rhizaria,protists,NaN,Uni,Plankton,Hetero,0.463432,8.263962,This study
18,Deep sea protist,protists,NaN,Uni,Plankton,Hetero,0.100000,10.000000,This study
19,Particle attached protists,protists,NaN,Uni,Particle,Hetero,0.158683,10.000000,This study
20,Protist macroalgae,protists,NaN,Multi,Benthic,Auto,0.208989,4.657959,This study
21,Heterotrophic pico-nanoplankton,protists,NaN,Uni,Plankton,Hetero,0.245478,NaN,This study
22,Epipelagic fungi,fungi,NaN,Uni,Plankton,Hetero,0.079223,NaN,This study
23,Deep sea fungi,fungi,NaN,Uni,Plankton,Hetero,0.055398,NaN,This study
24,Particle attached fungi,fungi,NaN,Uni,Particle,Hetero,0.112355,10.000000,This study
25,Viruses,viruses,NaN,Uni,Plankton,Hetero,0.034286,2.523886,This study

In [4]:
#CI_sum_prop(estimates=raw_data.loc[raw_data['Kingdom'] == 'Plants','Biomass'].values,mul_CIs=raw_data.loc[raw_data['Kingdom'] == 'Plants','Uncertainty'].values)
def integrate(x):
    x2 = x[['Biomass','Uncertainty']].dropna()
    
    return CI_sum_prop(x2['Biomass'].values,x2['Uncertainty'].values)
CI = raw_data.groupby('Kingdom').apply(integrate)
bio = raw_data.groupby('Kingdom')['Biomass'].sum()
agg_res = pd.concat([bio,CI],axis=1)
agg_res.columns = ['Biomass','Uncertainty']
agg_res.loc['fungi','Uncertainty'] = 10
agg_res.to_csv('../results/agg_data.csv')